version: '2'
services:
  web:
    build:
      context: .
    container_name: feed-app-frontend
    volumes:
      - .:/home/node/app
    ports:
      - 8081:3000
    environment:
      - ARTICLE_API_TIMEOUT=500
      - ARTICLE_API_HOST=http://localhost:8080/
 