version: 2

references:

jobs:
  ## Compile the app and push to docker repo
  build:
    machine: true
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t $DOCKER_IMAGE_URL:$CIRCLE_SHA1 .
      - run: docker push $DOCKER_IMAGE_URL:$CIRCLE_SHA1
  ## Run the unit tests
  test:
    machine: true
    steps:
      - checkout
  ## Deploy the app    
  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: mkdir -p /usr/local/google-cloud-sdk
      - run: ln -s /usr/bin /usr/local/google-cloud-sdk/bin
      - run: echo $GCLOUD_SERVICE_KEY > auth.json
      - run: chmod +x ./deployment/deploy.sh
      - run: bash ./deployment/deploy.sh
workflows:
  version: 2
  untagged-build:
    jobs:
      - build:
          filters:
            tags:
              ignore: /.*/
            branches:
              ignore: master
      - test:
          requires:
            - build
  tagged-build:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
            branches:
              only: master
      - test:
          requires:
            - build
      - hold:
          type: approval
          requires:
            - test
      - deploy:
          requires:
            - hold
